# Site settings
title: Jinru Wu
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I am Jinru, and this is my personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: danceronkeybd
github_username:  bleakwood
linkedin_profileid: 2876675

# Build settings
markdown: kramdown
